// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDslCSrtulsfTErfHq6V_kTxECNxgA6-p0',
    appId: '1:652606390756:web:669ad8e08391f1a09b07f1',
    messagingSenderId: '652606390756',
    projectId: 'chat-app-907a7',
    authDomain: 'chat-app-907a7.firebaseapp.com',
    storageBucket: 'chat-app-907a7.firebasestorage.app',
    measurementId: 'G-B9YJ908SDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM8kdXpWIRBDYGfCEK9gNdrJt0X_WmM1w',
    appId: '1:652606390756:android:7b4e2df2ecf410099b07f1',
    messagingSenderId: '652606390756',
    projectId: 'chat-app-907a7',
    storageBucket: 'chat-app-907a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTqBsV5Lf8P1N7eOLjcETV7LpvNLApP0g',
    appId: '1:652606390756:ios:b5bb394484ff06829b07f1',
    messagingSenderId: '652606390756',
    projectId: 'chat-app-907a7',
    storageBucket: 'chat-app-907a7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTqBsV5Lf8P1N7eOLjcETV7LpvNLApP0g',
    appId: '1:652606390756:ios:b5bb394484ff06829b07f1',
    messagingSenderId: '652606390756',
    projectId: 'chat-app-907a7',
    storageBucket: 'chat-app-907a7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDslCSrtulsfTErfHq6V_kTxECNxgA6-p0',
    appId: '1:652606390756:web:76b31b6ba6198d7d9b07f1',
    messagingSenderId: '652606390756',
    projectId: 'chat-app-907a7',
    authDomain: 'chat-app-907a7.firebaseapp.com',
    storageBucket: 'chat-app-907a7.firebasestorage.app',
    measurementId: 'G-30CQGMJLE3',
  );
}
