name: PushToTester

on:
  push:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Generate dynamic tag
        run: echo "TAG=v1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git tag $TAG
          git push origin $TAG

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          name: "Release ${{ env.TAG }}"
          body: "Automated build & release"
          files: build/app/outputs/flutter-apk/app-release.apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Testers
          file: build/app/outputs/flutter-apk/app-release.apk
