name: PushToTester

permissions:
  contents: write

on:
  push:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      # Generate the tag name
      - name: Generate dynamic tag
        run: echo "TAG=v1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      # Git needs user identity before pushing a tag
      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Create and push the tag
      - name: Create Git Tag
        run: |
          git tag $TAG
          git push origin $TAG

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          name: "Release ${{ env.TAG }}"
          body: "Automated build & release"
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Firebase App Distribution
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Testers
          file: build/app/outputs/flutter-apk/app-release.apk
